apiVersion: v1
kind: Service
metadata:
  name: smart-one-svc
spec:
  type: NodePort
  selector:
    app: smart-one-svc
  ports:
  - port: 8081
    nodePort: 30081
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: smart-one-svc-deployment
  labels:
    app: smart-one-svc
spec:
  replicas: 1
  selector:
    matchLabels:
      app: smart-one-svc
  template:
    metadata:
      labels:
        app: smart-one-svc
    spec:
      containers:
      - name: smart-one-svc
        image: us.icr.io/ns-rtrotter/smart-one-svc
        resources:
          requests:
            memory: "1Gi"
        ports:
        - containerPort: 8081
        
    